server:
  port: 8080

spring:
  application:
    name: luxury-enterprises-api
  datasource:
    url: jdbc:postgresql://localhost:5432/luxury_enterprises
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
